// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwkzqxsmlzivgrlpcnlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3a3pxeHNtbHppdmdybHBjbmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODA4OTUsImV4cCI6MjA2MTM1Njg5NX0.Q1lBnoRnXdPBHz1TESxfGbWCcGGVj3KVHnANQ7Lp5KA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);